namespace Core2.Symbolics.Conceptual;

public static class ConceptualLexicalMappingCatalog
{
    public static IReadOnlyList<ConceptualLexicalMappingDraft> All { get; } =
    [
        new(
            "inside",
            ConceptualSurfaceKind.Preposition,
            "container-interior",
            ConceptualRelationFamily.Containment,
            [ConceptualTopologyKind.Region, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Language],
            "Locate the figure in the interior region of a host rather than on its exterior or boundary.",
            "inside(figure, ground) := locate(figure, interior(frame(ground)))",
            "The toy is inside the box."),
        new(
            "near",
            ConceptualSurfaceKind.Preposition,
            "adjacency-band",
            ConceptualRelationFamily.Adjacency,
            [ConceptualTopologyKind.Region, ConceptualTopologyKind.Field],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Language],
            "Choose a lawful location from the surrounding admissible band near a target without occupying the target itself.",
            "near(figure, target) := choose(site in cover(target) NOT target)",
            "The lamp is near the chair."),
        new(
            "between",
            ConceptualSurfaceKind.Preposition,
            "between-interval",
            ConceptualRelationFamily.BoundedInterval,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Region],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Temporal, ConceptualLexicalDomain.Language],
            "Place the figure in the bounded interior defined by two anchors rather than relative to one landmark alone.",
            "between(figure, left, right) := locate(figure, interior(span(left, right)))",
            "The bridge sits between the towers."),
        new(
            "along",
            ConceptualSurfaceKind.Preposition,
            "along-host",
            ConceptualRelationFamily.PathCoincidence,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Through],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.Graph, ConceptualLexicalDomain.Language],
            "Constrain continuation so it follows a host carrier rather than cutting across open space.",
            "along(path, host) := continue(path) on carrier(host)",
            "The hikers moved along the river."),
        new(
            "through",
            ConceptualSurfaceKind.Preposition,
            "crossing-passage",
            ConceptualRelationFamily.Crossing,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Region, ConceptualTopologyKind.Through],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "Traverse a host by entering it, occupying some interior portion, and leaving it again.",
            "through(path, region) := enter(region) -> occupy(interior(region)) -> exit(region)",
            "The road passes through the forest."),
        new(
            "around",
            ConceptualSurfaceKind.Preposition,
            "surrounding-loop",
            ConceptualRelationFamily.SurroundClosure,
            [ConceptualTopologyKind.Loop, ConceptualTopologyKind.Region, ConceptualTopologyKind.Path],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.Ornamental, ConceptualLexicalDomain.Language],
            "Preserve a family of surrounding routes or a loose enclosure before selecting one exact folded path.",
            "around(path, target) := choose(loop in surround(target))",
            "They walked around the lake."),
        new(
            "during",
            ConceptualSurfaceKind.TemporalWord,
            "temporal-window",
            ConceptualRelationFamily.TemporalWindow,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Region],
            [ConceptualLexicalDomain.Temporal, ConceptualLexicalDomain.Language],
            "Read an event as occupying the interior of a temporal interval.",
            "during(event, interval) := occupy(event, interior(interval.start -> interval.end))",
            "During the storm, the lights flickered."),
        new(
            "until",
            ConceptualSurfaceKind.TemporalWord,
            "temporal-sequence",
            ConceptualRelationFamily.TemporalSequence,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Interval, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Temporal, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "Continue up to a cutoff or gate and stop, change, or wait at that boundary.",
            "until(process, boundary) := continue(process) while before(boundary)",
            "Wait until Friday."),
        new(
            "spanning",
            ConceptualSurfaceKind.TemporalWord,
            "temporal-window",
            ConceptualRelationFamily.TemporalWindow,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Path],
            [ConceptualLexicalDomain.Temporal, ConceptualLexicalDomain.Narrative, ConceptualLexicalDomain.Language],
            "Treat a duration as a covered interval rather than a point event.",
            "spanning(event, interval) := cover(interval) with event",
            "A strike spanning three days disrupted travel."),
        new(
            "approach",
            ConceptualSurfaceKind.MotionVerb,
            "source-path-goal",
            ConceptualRelationFamily.SourceGoal,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Interval],
            [ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.Language],
            "Continue toward a goal with decreasing separation, even before direct contact is achieved.",
            "approach(agent, goal) := continue(agent) with distance(goal) decreasing",
            "The train approached the station."),
        new(
            "exit",
            ConceptualSurfaceKind.MotionVerb,
            "boundary-crossing",
            ConceptualRelationFamily.Boundary,
            [ConceptualTopologyKind.Region, ConceptualTopologyKind.Path, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "Start in an interior region and cross outward through its boundary.",
            "exit(agent, region) := inside(agent, region) then cross(boundary(region)) to outside",
            "The crowd exited the building."),
        new(
            "cross",
            ConceptualSurfaceKind.MotionVerb,
            "crossing-passage",
            ConceptualRelationFamily.Crossing,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Region, ConceptualTopologyKind.Through],
            [ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.Graph, ConceptualLexicalDomain.Language],
            "Move from one side of a region, line, or guarded span to the other through lawful passage.",
            "cross(agent, host) := traverse(frame(host)) from one side to the other",
            "They crossed the border at dawn."),
        new(
            "x > 0",
            ConceptualSurfaceKind.EquationPattern,
            "ordered-comparison",
            ConceptualRelationFamily.Ordering,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "A comparison can be read as asking which side of a boundary on an ordered carrier the current state occupies.",
            "x > 0 := locate(x, positive_side(boundary(0)))",
            "The update takes the positive branch when x > 0."),
        new(
            "a <= x <= b",
            ConceptualSurfaceKind.EquationPattern,
            "between-interval",
            ConceptualRelationFamily.BoundedInterval,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Region, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "An interval test asks whether the current state lies inside a bounded admissible region instead of merely on one side of one threshold.",
            "a <= x <= b := locate(x, interior(span(a, b)))",
            "The solver accepts x when it remains inside the target window."),
        new(
            "(x > 0) and (x < 10)",
            ConceptualSurfaceKind.EquationPattern,
            "between-interval",
            ConceptualRelationFamily.BoundedInterval,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Region, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "Boolean conjunction over comparisons often reconstructs one bounded region by intersecting two half-space conditions.",
            "(x > 0) and (x < 10) := positive_side(boundary(0)) AND negative_side(boundary(10))",
            "Continue only while x remains in the interior band between 0 and 10."),
        new(
            "if x > 0 then A else B",
            ConceptualSurfaceKind.EquationPattern,
            "branch-merge-network",
            ConceptualRelationFamily.Branching,
            [ConceptualTopologyKind.Boundary, ConceptualTopologyKind.Branch, ConceptualTopologyKind.Path],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "A comparison at a boundary can trigger branch selection without changing the deeper idea of path continuation.",
            "branch(x @ boundary(0), positive -> A, nonpositive -> B)",
            "if x > 0 then accelerate else drift"),
        new(
            "x_{t+1} = x_t + step",
            ConceptualSurfaceKind.EquationPattern,
            "source-path-goal",
            ConceptualRelationFamily.SourceGoal,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Interval],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "A dynamic update is a traversal law on a carrier rather than only a static equality.",
            "advance(x_t) := x_t -> x_t + step",
            "Each tick moves the state one step further along the carrier."),
        new(
            "not inside target_band",
            ConceptualSurfaceKind.EquationPattern,
            "container-interior",
            ConceptualRelationFamily.Containment,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Region, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "Negation over a stopping band can be read as exterior occupancy relative to an active admissible region.",
            "not_inside(state, target_band) := NOT locate(state, interior(target_band))",
            "Keep searching while the state is still outside the acceptable band."),
        new(
            "repeat until inside target band",
            ConceptualSurfaceKind.EquationPattern,
            "obstruction-gate",
            ConceptualRelationFamily.Obstruction,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Interval, ConceptualTopologyKind.Region],
            [ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "The target band acts like a gate or stopping region that keeps the process active until the state enters it.",
            "loop(state) until locate(state, interior(target_band))",
            "Keep iterating until the state lies in the acceptable band."),
        new(
            "very tall",
            ConceptualSurfaceKind.ScalarModifier,
            "intensity-weighting",
            ConceptualRelationFamily.ScalarIntensity,
            [ConceptualTopologyKind.Interval, ConceptualTopologyKind.Field],
            [ConceptualLexicalDomain.Scalar, ConceptualLexicalDomain.Language],
            "Take a scalar extent reading and weight it more strongly rather than inventing a new dimension.",
            "very_tall(x) := weight(high, tall(x))",
            "The tower is very tall."),
        new(
            "upper management",
            ConceptualSurfaceKind.HierarchyTerm,
            "hierarchy-ladder",
            ConceptualRelationFamily.Hierarchy,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Field],
            [ConceptualLexicalDomain.Social, ConceptualLexicalDomain.Language],
            "Map organizational rank onto an oriented vertical band in an abstract social frame.",
            "upper_management := management @ upper_band(hierarchy(company))",
            "Upper management approved the change."),
        new(
            "close friend",
            ConceptualSurfaceKind.KinshipTerm,
            "adjacency-band",
            ConceptualRelationFamily.Adjacency,
            [ConceptualTopologyKind.Region, ConceptualTopologyKind.Field],
            [ConceptualLexicalDomain.Social, ConceptualLexicalDomain.Language],
            "Reuse proximity as an intimacy band inside social space rather than literal physical space.",
            "close_friend(person) := friend(person) in near_band(self.social_frame)",
            "She is a close friend."),
        new(
            "source-path-goal",
            ConceptualSurfaceKind.ImageSchema,
            "source-path-goal",
            ConceptualRelationFamily.SourceGoal,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Interval],
            [ConceptualLexicalDomain.Spatial, ConceptualLexicalDomain.Temporal, ConceptualLexicalDomain.Motion, ConceptualLexicalDomain.Equation, ConceptualLexicalDomain.Narrative, ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Language],
            "A reusable image schema for movement, planning, pursuit, process, and many narrative or control-flow readings.",
            "schema(source_path_goal) := source + path + goal + optional obstruction",
            "A program or equation advances from setup to completion, or a story moves from opening state toward a goal."),
        new(
            "blocked until open",
            ConceptualSurfaceKind.ControlCue,
            "obstruction-gate",
            ConceptualRelationFamily.Obstruction,
            [ConceptualTopologyKind.Region, ConceptualTopologyKind.Path, ConceptualTopologyKind.Boundary],
            [ConceptualLexicalDomain.ControlFlow, ConceptualLexicalDomain.Circuit, ConceptualLexicalDomain.Language],
            "Hold continuation at a gate until some condition releases the obstruction.",
            "blocked_until_open(flow, gate) := hold(flow) at gate until release(gate)",
            "Current is blocked until the switch closes."),
        new(
            "last week I was hoping to go on a 3 day holiday",
            ConceptualSurfaceKind.NarrativeCue,
            "temporal-sequence",
            ConceptualRelationFamily.TemporalSequence,
            [ConceptualTopologyKind.Path, ConceptualTopologyKind.Interval],
            [ConceptualLexicalDomain.Temporal, ConceptualLexicalDomain.Narrative, ConceptualLexicalDomain.Language],
            "Treat the remembered hope as a temporal span anchored in the recent past rather than a timeless proposition.",
            "hope_span := (7i - 4)  // starts seven days in the past and runs forward three days to end four days in the past",
            "Last week I was hoping to go on a 3 day holiday.")
    ];

    public static IReadOnlyList<ConceptualLexicalMappingDraft> ForSurface(ConceptualSurfaceKind surfaceKind) =>
        All.Where(mapping => mapping.SurfaceKind == surfaceKind).ToArray();

    public static IReadOnlyList<ConceptualLexicalMappingDraft> ForFamily(ConceptualRelationFamily family) =>
        All.Where(mapping => mapping.Family == family).ToArray();
}
